### ISSUE TITLE
Admob  compiled and linked with delphi XE 10.4 for android  : run time error

### ISSUE THREAD

**Issue by godsky1** [DelphiWorlds/Playground#9]
Code ::
procedure TfmAdTest.btnCreateClick(Sender: TObject);
begin
  // FAd.Load; // Not required for TAppOpenAd
  //AdMobBannerAd1.LoadAd;
  try
  //   FAd := TRewardedAd.Create;
  //   FAd := TRewardedInterstitialAd.Create;
     FAd := TInterstitialAd.Create;
  // FAd := TAppOpenAd.Create;
     FAd.TestMode := True;
     FAd.OnAdDismissedFullScreenContent := AdDismissedFullScreenContentHandler;
     FAd.OnAdFailedToShowFullScreenContent := AdFailedToShowFullScreenContentHandler;
     FAd.OnAdShowedFullScreenContent := AdShowedFullScreenContentHandler;
     FAd.OnAdFailedToLoad := OnFailToLoad;

     // RewardAds only
     //FAd.OnUserEarnedReward := UserEarnedRewardHandler;
     Memo.Lines.Add('Rewarded Ad component created success');
  except
  end;
end;

procedure TfmAdTest.ShowButtonClick(Sender: TObject);
begin
  AdMobBannerAd1.LoadAd;
  FAd.Load;
end;

LIB:: removed:
  com-google-android-gms-play-services-ads-base.17.0.2.0.dex.jar
  com-google-android-gms-play-services-ads-identifier.16.0.0.0.dex.jar
  com-google-android-gms-play-services-ads-lite.17.0.2.0.dex.jar
  com-google-android-gms-play-services-ads.17.0.2.0.dex.jar
  com-google-android-gms-play-services-ads-gass.17.0.2.0.dex.jar
LIB:: added:
  dw-admob.jar
  play-core-1.10.0,jar
  play-services-ads-20.1.0.jar
  play-services-ads-base-20.1.0.jar
  play-services-ads-identifier-20.1.0.jar
  play-services-ads-lite-20.1.0.jar

The AD created with no error.
When run AdMobBannerAd1.LoadAd after the ad created
error reported:   java.lang.NOClassDefFoundError:com.google.android.gms.internal.ads.zzcfi.

When run FAd.Load; after the ad created
 the app has no add show and has no error returned.  it seems dumbed.

**Comment by DelphiWorlds** [comment]
There is already a project for Delphi 10.4 (https://github.com/DelphiWorlds/Playground/tree/main/Demos/AdMob/D104) - you do not need to add or remove anything. In ShowButtonClick, you should only be calling one of `AdMobBannerAd1.LoadAd` or `FAd.Load`, not both, depending on what ad you want to show

**Comment by godsky1** [comment]
I also  compile and linked your example, but when I  run the app , it crashed at the beginning. 
I create a sample and copy your code , run with no crash, but when I click show button, it has no message return and no ad shows. I compare the setting , and found my app with the lib androd-support-v4.dex.jar added.   the app also crashed when I removed this lib.

**Comment by DelphiWorlds** [comment]
I retested the Delphi 10.4 demo and it works fine (unchanged) for me. The libraries as configured in the 10.4 demo are correct: you should not be disabling or adding anything else. If the demo as-is crashes, please provide exact details - run the app via the debugger and provide exact error messages (if any)

**Comment by godsky1** [comment]
can you send me your apk to me for testing ?   wangqs@163.com

**Comment by DelphiWorlds** [comment]
You can find a build of the Delphi 10.4 test project here:
https://github.com/DelphiWorlds/MiscStuff/blob/master/Test/AdTest.apk

**Comment by godsky1** [comment]
Hello, I test the app you built, it run OK,with android 10 and 11 ,but show nothing with android 8.  I add the event "FailToLoad" and add a button to show adBanner, other button to show rewarded video ad.  it return message 0: internal error with rewarded video ad and return java.lang.NOClassDefFoundError:com.google.android.gms.internal.ads.zzcfi. with adBanner.  can you publish a admob interface to compatible with most android version? for example, use the default gms of each android version.

**Comment by DelphiWorlds** [comment]
It works on my Android 8.1 device (Google Nexus 5X). What model device is yours? Is it a Huawei?

**Comment by godsky1** [comment]
Nexus6p  with android 8.0    and  Huawei with android 8.0

**Comment by godsky1** [comment]
android 10,11 is installed google Pixel 3, it runs OK. android 10 with Xiaomi(chinese market) return 0(internal error)

**Comment by godsky1** [comment]
Can you add GoogleApiAvailability.getInstance().isGooglePlayServicesAvailable  method to check the gms installed? if installed , you can get the gms version to decide what your API to do .  so you need not to package the gms lib when deploy your delphi app.

**Comment by DelphiWorlds** [comment]
You're welcome to add whatever calls you think will make it work

**Comment by godsky1** [comment]
Would you like to open source the java API of admob SDK lib for re-developing?

**Comment by DelphiWorlds** [comment]
I've just committed the Java source for the AdMob support: https://github.com/DelphiWorlds/Playground/tree/main/Java/AdMob

I doubt it will help you since they're just callback classes that needed to be written in Java. The rest of the AdMob support here is all Delphi code

**Comment by godsky1** [comment]
thanks， I  hope to know why the delphi xe  not to call the default gms which the phone installed, it package the fixed version gms library for different XE version.,

**Comment by godsky1** [comment]
I compared the gms between v8 and V20, and found the package name of then Ad class is different:
com.google.android.gms.ads.reward.RewardedVideoAd  8.0
com/google/android/gms/ads/rewarded/RewardedAd    20.0
com.google.android.gms.ads.InterstitialAd   8.0
com/google/android/gms/ads/interstitial/InterstitialAd  20.0
so If using the default gms package and the new bridge interface, the target function will ne not found.

if use the new interface and new gms package, I think some base function or class the new gms called may be not found in the old android library.

**Comment by DelphiWorlds** [comment]
See my earlier comment about support for Delphi 10.4. You need to disable the old jar libraries, and add the new ones. AdMob support has now been added to Kastri, so please refer any issues to [there](https://github.com/DelphiWorlds/Kastri/issues).
